apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.services.testService.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.services.testService.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.services.testService.label }}"
    spec:
      containers:
      - name: "{{ .Values.services.testService.label }}"
        image: "{{ .Values.registry }}/test-maker.{{ .Values.services.testService.label }}:{{ .Values.services.testService.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: testmaker-testservice-secret
          - secretRef:
              name: testmaker-common-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.services.eventService.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.services.eventService.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.services.eventService.label }}"
    spec:
      containers:
      - name: "{{ .Values.services.eventService.label }}"
        image: "{{ .Values.registry }}/test-maker.{{ .Values.services.eventService.label }}:{{ .Values.services.eventService.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: testmaker-eventservice-secret
          - secretRef:
              name: testmaker-common-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.services.userService.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.services.userService.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.services.userService.label }}"
    spec:
      containers:
      - name: "{{ .Values.services.userService.label }}"
        image: "{{ .Values.registry }}/test-maker.{{ .Values.services.userService.label }}:{{ .Values.services.userService.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: testmaker-userservice-secret
          - secretRef:
              name: testmaker-common-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.servers.identityServer.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.servers.identityServer.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.servers.identityServer.label }}"
    spec:
      containers:
      - name: "{{ .Values.servers.identityServer.label }}"
        image: "{{ .Values.registry }}/test-maker.{{ .Values.servers.identityServer.label }}:{{ .Values.servers.identityServer.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: testmaker-identityserver-secret
          - secretRef:
              name: testmaker-common-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.servers.apiGateway.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.servers.apiGateway.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.servers.apiGateway.label }}"
    spec:
      containers:
      - name: "{{ .Values.servers.apiGateway.label }}"
        image: "{{ .Values.registry }}/test-maker.{{ .Values.servers.apiGateway.label }}:{{ .Values.servers.apiGateway.tag }}"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.clients.dataTransfer.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.clients.dataTransfer.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.clients.dataTransfer.label }}"
    spec:
      containers:
      - name: "{{ .Values.clients.dataTransfer.label }}"
        image: "{{ .Values.registry }}/test-maker.{{ .Values.clients.dataTransfer.label }}:{{ .Values.clients.dataTransfer.tag }}"
        ports:
        - containerPort: 80
