apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.services.testService.label }}"
spec:
  selector:
    app: "{{ .Values.services.testService.label }}"
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.services.eventService.label }}"
spec:
  selector:
    app: "{{ .Values.services.eventService.label }}"
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ExternalName
  externalName: mongodb.server.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: ExternalName
  externalName: mssql.server.svc.cluster.local