apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: testmaker-testservice-connector
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.server.name: "mssql"
    database.hostname: "mssql.server.svc.cluster.local"
    database.port: "1433"
    database.user: "sa"
    database.password: "VanKinh1996"
    database.dbname: "TestMaker.TestService"
    table.include.list": ["UserQuestions"]
    database.history.kafka.bootstrap.servers: "cp-kafka:9092"
    database.history.kafka.topic: "schema-changes.testmaker-testservice"
