include: 'https://raw.githubusercontent.com/kinhnv/System.CommonPipeline/main/.prepare-ssh.yml'

stages:
  - publish-code

publish-code-job:
  stage: publish-code
  tags:
    - "shell"
  extends:
    - .prepare_ssh
  only:
    - main
  script:
    - git remote set-url origin $GITHUB_URL
    - git config core.packedGitLimit 512m;
    - git config core.packedGitWindowSize 512m;
    - git config pack.deltaCacheSize 2047m;
    - git config pack.packSizeLimit 2047m;
    - git config pack.windowMemory 2047m;
    - cat .git/config
    # - >
    #   if [ `git branch --list main` ]; then
    #     echo "push to existing branch"; 
    #     git push -u origin HEAD:main
    #   else
    #     echo "create new branch";
    #     git repack;
    #     git config --global core.compression 0;
    #     git checkout -b main; 
    #     git push -u origin main
    #   fi
