apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.services.userService.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.services.userService.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.services.userService.label }}"
    spec:
      containers:
      - name: "{{ .Values.services.userService.label }}"
        image: "{{ .Values.registry }}/{{ .Values.services.userService.label }}:{{ .Values.services.userService.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: user-service-secret
          - secretRef:
              name: common-secret