
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.services.userService.label }}"
spec:
  selector:
    app: "{{ .Values.services.userService.label }}"
  ports:
  - port: 80
    targetPort: 80