{{- range .Values.endPoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:  
  clusterIP: None
  ports:
  {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol  }}
  {{ end -}}
{{ end -}}
{{- range .Values.endPoints }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ .name }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
    {{- range .ports }}
      - name: {{ .name }}
        port: {{ .port }}
        protocol: {{.protocol  }}
    {{ end -}}
{{ end -}}
