{{- range .Values.servers -}}
{{ $portsLength := include "server.ports" .containers }}
{{- if gt (len $portsLength) 0 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .name }}"
spec:
  selector:
    app: "{{ .name }}"
  ports:
  {{- range $containerIndex, $containerValue := .containers }}
  {{- range $portIndex, $portValue := $containerValue.ports }}
  - name: poth-{{$containerIndex}}-{{ $portIndex }}
    targetPort: {{ $portValue.port }}
    {{- if $portValue.interalPort }}
    port: {{ $portValue.interalPort }}
    {{- end -}}
    {{- if not $portValue.interalPort }}
    port: {{ $portValue.port }}
    {{- end -}}
    {{- if $portValue.exteralPort }}
    nodePort: {{ $portValue.exteralPort }}
    {{- end -}}
  {{ end -}}
  {{ end }}
  {{ $exteralPortsLength := include "server.exteralPorts" .containers }}
  {{- if gt (len $exteralPortsLength) 0 -}}
  type: NodePort
  {{ end }}
{{ end -}}
{{ end -}}