registry: registry.gitlab.com
project:
  label: test-maker
services:
  testService:
    label: i3rothers/test-maker/test-service
    tag: "943845953"
  eventService:
    label: i3rothers/test-maker/event-Service
    tag: "932376997"
clients:
  dataTransfer:
    label: i3rothers/test-maker/data-transfer
    tag: "942393366"
