apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  vault-config.json: |
    {
      "backend": {
        "file": {
          "path": "/var/opt/vault/data"
        }
      },
      "listener": {
        "tcp":{
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "ui": true
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runnner
data:
  config.toml: |
    concurrent = 6
    check_interval = 0

    [session_server]
      session_timeout = 1800

    [[runners]]
      name = "gitlab-runner-brothers-shell"
      url = "https://gitlab.com/"
      id = 17466550
      token = "spsYrHskFAgPdRcUaZ7f"
      token_obtained_at = 2022-09-11T17:22:16Z
      token_expires_at = 0001-01-01T00:00:00Z
      executor = "shell"
      [runners.custom_build_dir]
      [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]
        [runners.cache.azure]

    [[runners]]
      name = "gitlab-runner-brothers-docker"
      url = "https://gitlab.com/"
      id = 17466551
      token = "4zymz_mqhqxiLRuC36Jy"
      token_obtained_at = 2022-09-11T17:22:16Z
      token_expires_at = 0001-01-01T00:00:00Z
      executor = "docker"
      [runners.custom_build_dir]
      [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]
        [runners.cache.azure]
      [runners.docker]
        host = "tcp://docker:2375"
        tls_verify = false
        image = "ubuntu"
        privileged = false
        disable_entrypoint_overwrite = false
        oom_kill_disable = false
        disable_cache = false
        volumes = ["/cache"]
        shm_size = 0
    [[runners]]
      name = "kinhnv-shell"
      url = "https://gitlab.com"
      id = 27322370
      token = "glrt-X15sc5Cdu2aJysP8mKqz"
      token_obtained_at = 2023-08-29T16:15:06Z
      token_expires_at = 0001-01-01T00:00:00Z
      executor = "shell"

    [[runners]]
      name = "kinhnv-docker"
      url = "https://gitlab.com"
      id = 27322370
      token = "glrt-X15sc5Cdu2aJysP8mKqz"
      token_obtained_at = 2023-08-29T16:15:45Z
      token_expires_at = 0001-01-01T00:00:00Z
      executor = "docker"
      [runners.cache]
        MaxUploadedArchiveSize = 0
      [runners.docker]
        host = "tcp://localhost:2375"
        tls_verify = false
        image = "ubuntu"
        privileged = false
        disable_entrypoint_overwrite = false
        oom_kill_disable = false
        disable_cache = false
        volumes = ["/cache"]
        shm_size = 0
