servers:
  - name: mssql
    revisionHistoryLimit: 0
    containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        tag: 2022-latest
        securityContext:
          runAsRoot: true
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            secret: server-mssql-secret
            key: password
            optional: false
          - name: MSSQL_AGENT_ENABLED
            value: true
        ports:
          - port: 1433
        volumes:
          - path: /var/opt/mssql/data
            nfs:
              path: "/data1/mssql"
              server: "192.168.1.7"
              storage: 10Gi
  - name: mongodb
    revisionHistoryLimit: 0
    containers:
      - name: mongodb
        image: mongo
        tag: 6.0.1
        securityContext:
          runAsRoot: true
        ports:
          - port: 27017
        envFrom:
          - secretRef:
              name: server-mongodb-secret
  - name: registry
    revisionHistoryLimit: 0
    containers:
      - name: registry
        image: registry
        tag: 2
        ports:
          - port: 5000
            interalPort: 30000
            exteralPort: 30000
  - name: vault
    revisionHistoryLimit: 0
    containers:
      - name: vault
        image: vault
        tag: 1.9.9
        ports:
          - port: 8200
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          runAsRoot: true
        args:
          - "server"
        volumes:
          - path: /vault/config/vault-config.json
            configMap: vault
            subPath: vault-config.json
          - path: /var/opt/vault/data
            nfs:
              path: "/data1/vault"
              server: "192.168.1.7"
              storage: 10Gi
  # - name: logstash
  #   revisionHistoryLimit: 0
  #   containers:
  #     - name: logstash
  #       image: 192.168.1.7:30000/logstash
  #       tag: "731857231"
  - name: gitlab-runner
    revisionHistoryLimit: 0
    containers:
      - name: gitlab-runner
        image: kinhnv1801/gitlab-runner
        tag: "1.0.4"
        env:
          - name: DOCKER_HOST
            value: tcp://docker:2375
        volumes:
          - path: /etc/gitlab-runner/config.toml
            configMap: gitlab-runnner
            subPath: config.toml
endPoints:
  - name: docker
    ip: 192.168.1.7
    ports:
      - name: docker
        port: 2375
        protocol: TCP
  - name: ssh
    ip: 192.168.1.7
    ports:
      - name: ssh
        port: 22
        protocol: TCP
