
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-gateway-ngrok"
spec:
  selector:
    matchLabels:
      app: "api-gateway-ngrok"
  template:
    metadata:
      labels:
        app: "api-gateway-ngrok"
    spec:
      containers:
      - name: "api-gateway-ngrok"
        image: ngrok/ngrok:alpine
        env:
          - name: TYPE
            value: http
          - name: HOST
            value: "api-gateway.common.svc.cluster.local"
          - name: PORT
            value: "80"
          - name: NGROK_AUTHTOKEN
            value: "2AcXLYoUwj7zsEhnAsB859vDL3W_5XUvNgYTuCRCdQm5gaWNC"
          - name: GITHUB_FILE
            value: "api-gateway.json"
          - name: GITHUB_NGROK_SOURCE
            value: "git@github.com:kinhnv/Platform.Ngrok.git"
        envFrom:
          - secretRef:
              name: common-secret
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint

