apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-ngrok
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: elasticsearch-ngrok
  template:
    metadata:
      labels:
        app: elasticsearch-ngrok
    spec:
      containers:
      - name: elasticsearch-ngrok
        image: ngrok/ngrok:alpine
        env:
          - name: TYPE
            value: http
          - name: HOST
            value: "elasticsearch.server.svc.cluster.local"
          - name: PORT
            value: "9200"
          - name: NGROK_AUTHTOKEN
            value: "2BYMZB12Gz6IVzJdBBMeKORDcZA_2ec2UNWQMbNZiRm28dQjt"
          - name: GITHUB_FILE
            value: "elasticsearch.json"
        envFrom:
          - secretRef:
              name: ngrok-common-secret
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint


