
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "file-server-ngrok"
spec:
  selector:
    matchLabels:
      app: "file-server-ngrok"
  template:
    metadata:
      labels:
        app: "file-server-ngrok"
    spec:
      containers:
      - name: "file-server-ngrok"
        image: ngrok/ngrok:alpine
        env:
          - name: TYPE
            value: http
          - name: HOST
            value: "identity-server.common.svc.cluster.local"
          - name: PORT
            value: "80"
          # identityserver.brothers.80@gmail.com
          - name: NGROK_AUTHTOKEN
            value: "2SkGvzTRczt3jBYXithy6A3SFGQ_2E4QQhCa7oBD2Cji7Z6ML"
          - name: GITHUB_FILE
            value: "file-server.json"
        envFrom:
          - secretRef:
              name: ngrok-common-secret
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint

