
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "identity-server-ngrok"
spec:
  selector:
    matchLabels:
      app: "identity-server-ngrok"
  template:
    metadata:
      labels:
        app: "identity-server-ngrok"
    spec:
      containers:
      - name: "identity-server-ngrok"
        image: ngrok/ngrok:alpine
        envFrom:
          - secretRef:
              name: common-secret
        env:
          - name: TYPE
            value: http
          - name: HOST
            value: "identity-server.common.svc.cluster.local"
          - name: PORT
            value: "80"
          # identityserver.brothers.80@gmail.com
          - name: NGROK_AUTHTOKEN
            value: "2SabxVWz6eKBovyICJkexjbfmEd_6FRkuMYqBaYciqJ6jur4t"
          - name: GITHUB_NGROK_SOURCE
            value: "git@github.com:kinhnv/Platform.Ngrok.git"
        envFrom:
          - secretRef:
              name: common-secret
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint

