apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaui-ngrok
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kafkaui-ngrok
  template:
    metadata:
      labels:
        app: kafkaui-ngrok
    spec:
      containers:
      - name: kafkaui-ngrok
        image: ngrok/ngrok:alpine
        envFrom:
          - secretRef:
              name: common-secret
        env:
          - name: TYPE
            value: http
          - name: HOST
            value: "kafka-ui.kafka.svc.cluster.local"
          - name: PORT
            value: "8080"
          - name: NGROK_AUTHTOKEN
            value: "2KUjbxalbUU6uHWIzwzdBWzdd6h_7LoDg6oNaikwW78pyufin"
          - name: GITHUB_NGROK_SOURCE
            value: "git@gitlab.com:i3rothers/platform/ngrok.git"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint


