apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-ngrok
spec:
  selector:
    matchLabels:
      app: mongodb-ngrok
  template:
    metadata:
      labels:
        app: mongodb-ngrok
    spec:
      containers:
      - name: mongodb-ngrok
        image: ngrok/ngrok:alpine
        env:
          - name: HOST
            value: "mongodb.server.svc.cluster.local"
          - name: PORT
            value: "27017"
          - name: NGROK_AUTHTOKEN
            value: "2Bn9nDSWbGhjW6VMiP2x0ue5ua0_JWkdWZ4mJARotqUFnExt"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "ngrok tcp $HOST:$PORT --log=stdout"]
