apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-ngrok
spec:
  selector:
    matchLabels:
      app: mongodb-ngrok
  template:
    metadata:
      labels:
        app: mongodb-ngrok
    spec:
      containers:
      - name: mongodb-ngrok
        image: ngrok/ngrok:alpine
        env:
          - name: TYPE
            value: tcp
          - name: HOST
            value: "mongodb.server.svc.cluster.local"
          - name: PORT
            value: "27017"
          - name: NGROK_AUTHTOKEN
            value: "2Bn9nDSWbGhjW6VMiP2x0ue5ua0_JWkdWZ4mJARotqUFnExt"
        envFrom:
          - secretRef:
              name: common-secret
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint


