apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-ngrok
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vault-ngrok
  template:
    metadata:
      labels:
        app: vault-ngrok
    spec:
      containers:
      - name: vault-ngrok
        image: ngrok/ngrok:alpine
        env:
          - name: TYPE
            value: http
          - name: HOST
            value: "vault.server.svc.cluster.local"
          - name: PORT
            value: "8200"
          - name: NGROK_AUTHTOKEN
            value: "2Bn8Z3MzNBcGCbgJB6lU7qpWh5a_3eH4EeiM2iiVNNajKUaHW"
          - name: GITHUB_FILE
            value: "vault.json"
        envFrom:
          - secretRef:
              name: ngrok-common-secret
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "/custom-entrypoint.sh"]
        volumeMounts:
        - name: custom-entrypoint
          mountPath: /custom-entrypoint.sh
          subPath: custom-entrypoint.sh
        - name: push-ngrok-endpoint
          mountPath: /push-ngrok-endpoint.sh
          subPath: push-ngrok-endpoint.sh
      volumes:
      - configMap:
          defaultMode: 511
          name: custom-entrypoint
        name: custom-entrypoint
      - configMap:
          defaultMode: 511
          name: push-ngrok-endpoint
        name: push-ngrok-endpoint

