apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.servers.apiGateway.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.servers.apiGateway.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.servers.apiGateway.label }}"
    spec:
      containers:
      - name: "{{ .Values.servers.apiGateway.label }}"
        image: "{{ .Values.registry }}/{{ .Values.servers.apiGateway.label }}:{{ .Values.servers.apiGateway.tag }}"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.servers.identityServer.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.servers.identityServer.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.servers.identityServer.label }}"
    spec:
      containers:
      - name: "{{ .Values.servers.identityServer.label }}"
        image: "{{ .Values.registry }}/{{ .Values.servers.identityServer.label }}:{{ .Values.servers.identityServer.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: identity-server-secret
          - secretRef:
              name: common-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.servers.fileServer.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.servers.fileServer.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.servers.fileServer.label }}"
    spec:
      containers:
      - name: "{{ .Values.servers.fileServer.label }}"
        image: "{{ .Values.registry }}/{{ .Values.servers.fileServer.label }}:{{ .Values.servers.fileServer.tag }}"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: file-server-secret
          - secretRef:
              name: common-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.clients.dataTransfer.label }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.clients.dataTransfer.label }}"
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.clients.dataTransfer.label }}"
    spec:
      containers:
      - name: "{{ .Values.clients.dataTransfer.label }}"
        image: "{{ .Values.registry }}/{{ .Values.clients.dataTransfer.label }}:{{ .Values.clients.dataTransfer.tag }}"
        ports:
        - containerPort: 80