kind: Secret
apiVersion: v1
metadata:
  name: server-mongodb-secret
  namespace: server
  annotations:
    avp.kubernetes.io/path: "server/data/mongodb"
type: Opaque
stringData:
  MONGO_INITDB_ROOT_PASSWORD: <MONGO_INITDB_ROOT_PASSWORD>
  MONGO_INITDB_ROOT_USERNAME: <MONGO_INITDB_ROOT_USERNAME>