kind: Secret
apiVersion: v1
metadata:
  name: testmaker-identityserver-secret
  namespace: test-maker
  annotations:
    avp.kubernetes.io/path: "/test-maker/data/identity-server"
type: Opaque
stringData:
  TM_IDENTITY_SERVER_SQL_DB: <TM_IDENTITY_SERVER_SQL_DB>