kind: Secret
apiVersion: v1
metadata:
  name: testmaker-eventservice-secret
  namespace: test-maker
  annotations:
    avp.kubernetes.io/path: "/test-maker/data/event-service"
type: Opaque
stringData:
  TM_EVENT_SERVICE_SQL_DB: <TM_EVENT_SERVICE_SQL_DB>