registry: registry.gitlab.com/i3rothers/common
project:
  label: common
servers:
  apiGateway:
    label: api-gateway
    tag: "947638426"
  identityServer:
    label: identity-server
    tag: "932290389"
  fileServer:
    label: file-server
    tag: "937662871"
services:
  identityServer:
    tag: "947657545"
