registry: registry.gitlab.com/i3rothers/common
project:
  label: common
servers:
  apiGateway:
    label: api-gateway
    tag: "947638426"
  identityServer:
    label: identity-server
    tag: "947717798"
  fileServer:
    label: file-server
    tag: "947720442"
clients:
  dataTransfer:
    label: data-transfer
    tag: "1113502346"
